### ISSUE TITLE
Error Message: At least one of your two-factor authentication methods could not be loaded. Contact your administrator.

### ISSUE THREAD

**Issue by Kev-kr** [nextcloud/twofactor_webauthn#142]
### Steps to reproduce
After Upgrading to 0.3.1

### Expected behaviour
No error message, forwarding to the 2nd factor

### Actual behaviour
Staying in the selection screen, error message "that at least one authentication methods won't load", but selecting Webauthn as authentication methode still works. Just the error message is annoying
![error](https://user-images.githubusercontent.com/94394071/157227298-d1aaadae-39a8-41ce-ac02-af51f722bdba.PNG)

### Server configuration

**Operating system**: Raspbian (32 bit, Buster)

**Web server:** Apache2

**Database:** mysql

**PHP version:** 7.3.31

**Version:** 22.2.5

**Updated from an older version

**List of activated apps:**

```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - calendar: 3.1.0
  - circles: 22.2.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.8
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.20.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.4.0
  - impersonate: 1.9.0
  - integration_reddit: 1.0.3
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.11.7
  - music: 1.5.1
  - nextcloud_announcements: 1.11.0
  - notes: 4.3.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.3.2
  - password_policy: 1.12.0
  - passwords: 2021.12.10
  - podcast: 0.0.1
  - previewgenerator: 102.2.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.3
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - theming_customcss: 1.10.0
  - twofactor_admin: 3.2.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - twofactor_webauthn: 0.3.1
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external: 1.11.1
  - nextcloudpi: 0.0.1
  - photos: 1.2.1
  - previewgenerator.orig
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'passwordsalt' => '*',
  'secret' => '*',
  'trusted_domains' =>
  array (
    0 => '*',
    1 => '*',
    5 => '*',
    7 => '*',
    12 => '*',
    13 => '*',
    11 => '*',
    14 => '*',
    3 => '*',
  ),
  'datadirectory' => '/media/Drive/ncdata',
  'dbtype' => 'mysql',
  'version' => '22.2.5.1',
  'overwrite.cli.url' => '*',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '*',
  'dbpassword' => '*',
  'installed' => true,
  'instanceid' => '*',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
    'password' => '*',
  ),
  'tempdirectory' => '/media/Drive/ncdata/tmp',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => '*',
  'mail_domain' => '*',
  'preview_max_x' => '2048',
  'preview_max_y' => '2048',
  'jpeg_quality' => '60',
  'overwriteprotocol' => 'https',
  'maintenance' => false,
  'logfile' => '/media/Drive/ncdata/nextcloud.log',
  'loglevel' => '2',
  'log_type' => 'file',
  'htaccess.RewriteBase' => '/',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'ssl',
  'mail_smtphost' => '*',
  'mail_smtpport' => '465',
  'mail_smtpname' => '*',
  'mail_smtppassword' => '*',
  'theme' => '',
  'updater.release.channel' => 'stable',
  'data-fingerprint' => '*',
  'default_phone_region' => 'DE',
  'auth.webauthn.enabled' => false,
  'app_install_overwrite' =>
  array (
    0 => 'podcast',
    1 => 'nextcloudpi',
    2 => 'previewgenerator',
  ),
);
```

#### Client configuration
**Browser:**

Chrome Version 99.0.4844.51 (Offizieller Build) (64-Bit)

**Operating system:**

Windows 10 (64 bit)

##### Server log (data/nextcloud.log)
```
{"reqId":"Yidn7VTfV8SzpHjVPf@IJQAAEAw","level":3,"time":"2022-03-08T14:28:01+00:00","remoteAddr":"*","user":"*","app":"core","method":"POST","url":"/login","message":"two-factor auth provider 'twofactor_webauthn' failed to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"Yidn7VTfV8SzpHjVPf@IJQAAEAw","level":3,"time":"2022-03-08T14:28:01+00:00","remoteAddr":"*","user":"*","app":"core","method":"POST","url":"/login","message":"1 two-factor auth providers failed to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"Yidn8VTfV8SzpHjVPf@IKAAAFQw","level":3,"time":"2022-03-08T14:28:01+00:00","remoteAddr":"*","user":"*","app":"core","method":"GET","url":"/login/selectchallenge","message":"two-factor auth provider 'twofactor_webauthn' failed to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"Yidn8VTfV8SzpHjVPf@IKAAAFQw","level":3,"time":"2022-03-08T14:28:01+00:00","remoteAddr":"*","user":"*","app":"core","method":"GET","url":"/login/selectchallenge","message":"1 two-factor auth providers failed to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"Yidn8VTfV8SzpHjVPf@IKgAADgw","level":3,"time":"2022-03-08T14:28:02+00:00","remoteAddr":"*","user":"*","app":"core","method":"GET","url":"/login/selectchallenge?redirect_url=/apps/accessibility/css/user-*","message":"two-factor auth provider 'twofactor_webauthn' failed to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}
{"reqId":"Yidn8VTfV8SzpHjVPf@IKgAADgw","level":3,"time":"2022-03-08T14:28:02+00:00","remoteAddr":"*","user":"*","app":"core","method":"GET","url":"/login/selectchallenge?redirect_url=/apps/accessibility/css/user-*","message":"1 two-factor auth providers failed to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"22.2.5.1"}

```

**Comment by PatrickJosh** [comment]
I can confirm this issue with Nextcloud 23.0.2. It happens since the update of twofactor_webauthn to 0.3.1.

**Comment by lsch0l3y** [comment]
I also can confirm this issue. In addition, if the app is removed, or disabled, Nextcloud logs the following:

2 two-factor auth providers failed to load

two-factor auth provider 'webauthn' failed to load

two-factor auth provider 'twofactor_webauthn' failed to load

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/twofactor_webauthn/blob/684bf7ef21b6c6276a71cf52a76686b67b3e1024/lib/Provider/WebauthnProvider.php#L133 in the old version vs https://github.com/nextcloud/twofactor_webauthn/blob/27977e5ffef14f2d280628ff51c4728e300d8a1d/lib/Provider/WebAuthnProvider.php#L78 in the new one.

My bad. I cleaned up the code and streamlined the identified without thinking of the consequences.

**Comment by ChristophWurst** [comment]
The problem is that if I switch back from `webauthn` to `twofactor_webauthn`, eveyone who set up a device since 0.3 will run into the same problem :/

**Comment by Kev-kr** [comment]
> The problem is that if I switch back from `webauthn` to `twofactor_webauthn`, eveyone who set up a device since 0.3 will run into the same problem :/

Is it possible to release an Update or an Update instruction to fix it or will the Problem stay forever?
Maybe releasing two different version of the app?

**Comment by ChristophWurst** [comment]
I'll figure something out.

**Comment by mrclschstr** [comment]
As a preparation for the Nextcloud 24 upgrade I migrated all existing U2F registrations to WebAuthn like mentioned in the [README](https://github.com/nextcloud/twofactor_webauthn#migration-from-two-factor-u2f). To check the successful migration I ran the command `occ twofactorauth:state` with my user and got the following result:

```
Two-factor authentication is enabled for user XXX

Enabled providers:
- backup_codes
- totp
- webauthn
Disabled providers:
- twofactor_webauthn
```

I have _not_ set up passwordless WebAuthn authentication but I'm confused with the enabled `webauthn` and disabled `twofactor_webauthn` providers. Does this correlate with the renamed provider identifier?

**Comment by PatrickJosh** [comment]
If this should have been fixed by updating to 0.3.2 (as indicated in #259), then it hasn't worked for me. I still get the same error on every login. The result of `occ twofactorauth:state` with my username is the following:
```
Enabled providers:
- backup_codes
- twofactor_webauthn
- webauthn
Disabled providers:
- totp
```

**Comment by ChristophWurst** [comment]
Do you get any warning when you run `occ maintenance:repair` manually?

**Comment by PatrickJosh** [comment]
No. I don't see anything related to webauthn or two-factor authentication in the output.

**Comment by ChristophWurst** [comment]
Okay. So the repair step is not run at all.

**Comment by ChristophWurst** [comment]
I can't figure out why but the repair step runs for Nextcloud 25 but not Nextcloud 24.

**Comment by inok16** [comment]
I run Nextcloud 23.0.9.1 and it does not work for me aswell.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/twofactor_webauthn/pull/264 fixes that. the first backport to stable0.3 was bogus.

**Comment by ChristophWurst** [comment]
Please try v0.3.3

**Comment by PatrickJosh** [comment]
With v0.3.3, it worked for me. I don't get the error any more. Thank you very much! :smile:

**Comment by inok16** [comment]
With v0.3.3, I still have the problem. But it seems that my configuration/state is faulty and/or contains the old u2f provider. The u2f app is not present anymore.
```
Two-factor authentication is enabled for user x

Enabled providers:
- backup_codes
- u2f
- webauthn
```

Any ideas? Thanks in advance!

**Comment by ChristophWurst** [comment]
@inok16 please read the docs at https://github.com/nextcloud/twofactor_webauthn#migration-from-two-factor-u2f

**Comment by inok16** [comment]
yes, I know the documentation, but not at the time I installed webauthn. Thats why I did not migrate from U2F. At some later point, I deinstalled U2F. But as I can see right now, the provider seems still to be there.

Fortunately, 'php occ twofactorauth:cleanup u2f' solved it. Thanks.
