### ISSUE TITLE
"Don't ask to plug in the device", automatic auth

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_webauthn#164]
### Feature Request

Add a USER preference  "Don't ask me to plug in the device (since I keep it plugged-in all the time)"

#### Summary

I think there are two use cases:

1. The WebAuthn device is plugged-in permanently in a laptop
2. The WebAuthn device is carried like a classical key in the user's pocket

Personally, I'm case 1. I want to streamline the login process. Each additional step is a burden. So as a USER, I'd like to be able to set a preference "Don't ask me to plug in the device since it's plugged-in all the time" or similar.

The current login flow and 2FA sub flow has too many clicks. Steps:

1. username, password, KLICK
2. (if more than one is active) SELECT 2FA challenge
3. (if twofactor_webauthn is used) START (in order to be able to plug in the device first)
4. hit the device (or even enter a PIN)

I suggest to be able to get rid of step 3. for the use case 1.

**Comment by mike2307** [comment]
I think it was exactly like that in an older version.
Would appreciate if we could have an option to restore that behavior! :)

**Comment by jancborchardt** [comment]
If this is technically possible, we should indeed to it – not as a preference though, but automatically.

**Comment by nursoda** [comment]
> If this is technically possible, we should indeed to it – not as a preference though, but automatically.

Suits my usage, but I'm unsure if this suits all users: ARE there use cases that need to prompt a user to plug in his device first? IF so, the default might be not to prompt and an option to prompt would be nice.
