### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/twofactor_webauthn#178]
### Feature Request

The app is nearing feature completeness with the old U2F app. So it's time to have a closer look at the visuals together with the design team.

@nimishavijay @jancborchardt would have time for this in an upcoming weekly design call?

#### Summary

Review the app and create tickets for everything that should change.

**Comment by nimishavijay** [comment]
Sounds good, scheduled it for 31.05 (the Tuesday after the coming week) in the design channel, hope it works for all involved :)

**Comment by ChristophWurst** [comment]
Thanks!

**Comment by coelner** [comment]
If it matches the topic:
- an option to rename the device
- an information for which domain the device was registered (but only if multiple domains are used)

**Comment by ChristophWurst** [comment]
Closing this ticket in favor of the new tasks
