### ISSUE TITLE
Link to help forum does not work

### ISSUE THREAD

**Issue by eehmke** [nextcloud/twofactor_webauthn#18]
The link on 
https://apps.nextcloud.com/apps/twofactor_webauthn
leading to the help forum
https://help.nextcloud.com/c/apps/twofactor-webauthn
Does not work.

**Comment by michib** [comment]
Oh i didn't know there is even a link to a forum, must be a default value. Thanks for pointing this out

**Comment by ChristophWurst** [comment]
https://help.nextcloud.com/c/apps/twofactor-webauthn/181 exists now
