### ISSUE TITLE
Add NC 25 support

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_webauthn#253]

**Comment by nursoda** [comment]
In 1.0.0-beta,1, the button is misaligned:

![grafik](https://user-images.githubusercontent.com/8425483/191538652-e07fed6b-5427-4a0b-a73d-fd6d5793989d.png)

However, I thought that the button shall be omitted altogether?!

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/twofactor_webauthn/pull/257 & https://github.com/nextcloud/twofactor_webauthn/pull/210

**Comment by nursoda** [comment]
beta.2 is perfect in both respects, thanks!

**Comment by nursoda** [comment]
Since NC25.0.0-RC1, the colors are reverse again.using Webauthn 1.0.0-beta2
![grafik](https://user-images.githubusercontent.com/8425483/193263969-f02662b2-d42e-4664-a775-c2fea9e2e695.png)
