### ISSUE TITLE
l10n: Context needed for translation

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/twofactor_webauthn#328]
https://github.com/nextcloud/twofactor_webauthn/blob/0ded6ef0abdfbe37b56d77e393eb47bef9f476d9/src/components/AddDeviceDialog.vue#L38

Translators at Transifex ask for the meaning.

`Please use your security key authorisation.` Is it about pressing the button of the key?
Or `Please use your security key to authorize.` ?

**Comment by ChristophWurst** [comment]
> Is it about pressing the button of the key?

Not every key has a button. Some have to inserted another time. That is why we phrased it this way. IIRC we used a similar phrase as seen in Chrome.

**Comment by silopolis** [comment]
Or is that `Please use your security key for authorization.` ?
Maybe even `Please use your security key for authorization, pressing its button or reinserting it.` ?

**Comment by ChristophWurst** [comment]
I vote for 2.
