### ISSUE TITLE
Migration failed

### ISSUE THREAD

**Issue by Somebodyisnobody** [nextcloud/twofactor_webauthn#334]
### Question
Hi, I just tried to migrate from u2f to Two-Factor WebAuthn following this manual: https://github.com/nextcloud/twofactor_webauthn#migration-from-two-factor-u2f
Now the error "authentication modules couldn't be loaded" isn't thrown anymore and I get the OS-window which wants me to press my key to confirm login. Unfortunally this goes in a loop. So after authorizing the login on the hardware key i need to do it again and again.

Now I took a look into my logs (errors appeared multiple times, highest one = last one):
<details>
<summary>Exception: OC\Core\Controller\LoginController::tryLogin(): Argument # 1 ($user) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/core/Controller/LoginController.php' line 298</summary>

```
Exception: OC\Core\Controller\LoginController::tryLogin(): Argument # 1 ($user) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/core/Controller/LoginController.php' line 298

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1047:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()

Verursacht durch TypeError: OC\Core\Controller\LoginController::tryLogin(): Argument #1 ($user) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:

    OC\Core\Controller\LoginController->tryLogin("*** sensiti ... *")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1047:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()
```
</details>
<details>
<summary>Assert\InvalidArgumentException: The credential ID is invalid.</summary>

```
Assert\InvalidArgumentException: The credential ID is invalid.

    /var/www/nextcloud/apps/twofactor_webauthn/vendor/beberlei/assert/lib/Assert/Assertion.php - line 721:

    Assert\Assertion::createException()

    /var/www/nextcloud/apps/twofactor_webauthn/vendor/web-auth/webauthn-lib/src/AuthenticatorAssertionResponseValidator.php - line 113:

    Assert\Assertion::notNull()

    /var/www/nextcloud/apps/twofactor_webauthn/lib/Service/WebAuthnManager.php - line 350:

    Webauthn\AuthenticatorAssertionResponseValidator->check()

    /var/www/nextcloud/apps/twofactor_webauthn/lib/Provider/WebAuthnProvider.php - line 118:

    OCA\TwoFactorWebauthn\Service\WebAuthnManager->finishAuthenticate()

    /var/www/nextcloud/lib/private/Authentication/TwoFactorAuth/Manager.php - line 268:

    OCA\TwoFactorWebauthn\Provider\WebAuthnProvider->verifyChallenge("*** sensiti ... *")

    /var/www/nextcloud/core/Controller/TwoFactorChallengeController.php - line 182:

    OC\Authentication\TwoFactorAuth\Manager->verifyChallenge("*** sensiti ... *")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:

    OC\Core\Controller\TwoFactorChallengeController->solveChallenge("*** sensiti ... *")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1047:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()
```
</details>
<details>
<summary>Exception: Call to a member function getUserHandle() on null in file '/var/www/nextcloud/apps/twofactor_webauthn/lib/Service/WebAuthnManager.php' line 365</summary>

```
Exception: Call to a member function getUserHandle() on null in file '/var/www/nextcloud/apps/twofactor_webauthn/lib/Service/WebAuthnManager.php' line 365

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1047:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()

Verursacht durch Error: Call to a member function getUserHandle() on null

    /var/www/nextcloud/apps/twofactor_webauthn/lib/Controller/SettingsController.php - line 82:

    OCA\TwoFactorWebauthn\Service\WebAuthnManager->removeDevice()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:

    OCA\TwoFactorWebauthn\Controller\SettingsController->remove()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1047:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()
```
</details>
<details>
<summary>Exception: OC\Core\Controller\WebAuthnController::finishAuthentication(): Argument # 1 ($data) must be of type string, null given</summary>

```
Exception: OC\Core\Controller\WebAuthnController::finishAuthentication(): Argument # 1 ($data) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/nextcloud/core/Controller/WebAuthnController.php' line 88

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1047:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()

Verursacht durch TypeError: OC\Core\Controller\WebAuthnController::finishAuthentication(): Argument #1 ($data) must be of type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:

    OC\Core\Controller\WebAuthnController->finishAuthentication()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1047:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()
```
</details>

My SSH console log is following:
```
# sudo -u www-data php occ twofactorauth:state myuser
Two-factor authentication is enabled for user myuser

Enabled providers:
- backup_codes
- u2f
- webauthn
# sudo -u www-data php occ twofactor_webauthn:migrate-u2f --all
Migrating all devices of all users ...
Migrating devices of user myuser
Migrating devices of user myuser2
Migrating devices of user myuser3
Migrating devices of user myuser4
# sudo -u www-data php occ app:disable twofactor_u2f
No such app enabled: twofactor_u2f
# sudo -u www-data php occ twofactorauth:cleanup u2f
All user-provider associations for provider u2f have been removed.
#

```

My user accounts security section looks like following:
<kbd>
![grafik](https://user-images.githubusercontent.com/35230554/213568641-d41ecbd7-6d77-479a-a4a7-b07261674587.png)
</kbd>
I cannot remove the "Stick" or "Stick2" entries, it disappears but when I reload it's there again. The remove action throws an HTTP 500 and `Call to a member function getUserHandle() on null in file '/var/www/nextcloud/apps/twofactor_webauthn/lib/Service/WebAuthnManager.php' line 365`.
<kbd>
![grafik](https://user-images.githubusercontent.com/35230554/213569277-7181e169-c442-4949-b254-1c8167b89de6.png)
</kbd>
The YubiKey I've added (shown in the screenshot) is set up but newly after migration (the old instance is the "Stick" entry) but I cannot login with it (looping like described). Adding the YubiKey as 2fa method results in endless loading spinner after touching the key.

As you could see I have multiple users on my cloud instance. How can I repair this now? Can I recover the "Stick" entries?

My environment: 
![grafik](https://user-images.githubusercontent.com/35230554/213570137-0bb0c0f3-76db-4624-8299-f2e3a7141579.png)
[Nextcloud Hub 3](https://nextcloud.com/) (25.0.2)

#### Summary

After migrating from u2f to this app I have dead entries in my list of devices and I cannot login anymore altrough I have set up one of my keys again.

**Comment by Somebodyisnobody** [comment]
So here is no progress on my question how to repair the database.
Can anybody at least give me a manual how to remove the 2FA user data to "factory reset" 2FA? I think I have to delete some keys.

**Comment by Somebodyisnobody** [comment]
@ChristophWurst maybe you can help answer me this. I saw that I've more than just one table like described [here in forum](https://help.nextcloud.com/t/solved-2fa-not-working-anymore-after-reinstall/104639/3):
![grafik](https://user-images.githubusercontent.com/35230554/216718472-87ed6105-44e5-4f03-bbc6-4453bceb41af.png)
I also found in the web that truncating nc_twofactor_providers would make users cannot login anymore.
Can you tell me which tables I have to clear to reset the 2FA and Webauthn apps? This would help me a lot.

**Comment by ChristophWurst** [comment]
php occ app:disable twofactor_webauthn
php occ twofactorauth:clear webauthn

**Comment by Somebodyisnobody** [comment]
Hi @ChristophWurst, thanks for your help. "clear" is an unknown command but I ran "cleanup". That removed the webauthn devices "Yubikey" and "Stick".
```
# sudo -u www-data php occ twofactorauth:cleanup webauthn
All user-provider associations for provider webauthn have been removed.
```

The "Stick2" entries are still there so i listed the active providers for my user:
```
# sudo -u www-data php occ twofactorauth:state myuser
Two-factor authentication is enabled for user myuser

Enabled providers:
- backup_codes
- webauthn
```

and also run the cleanup for the provider backup_codes:
```
# sudo -u www-data php occ twofactorauth:cleanup backup_codes
All user-provider associations for provider backup_codes have been removed.
```

However the "Stick2" entries are still active:
![grafik](https://user-images.githubusercontent.com/35230554/221406998-0995b391-4ab5-4021-b4b5-8c11cd1d3157.png)

I think there is another unknown provider which left orphaned entries. Any idea how to solve this?

**Comment by Somebodyisnobody** [comment]
So I was brave and fired:
```
TRUNCATE TABLE nc_twofactor_u2f_registrations;
TRUNCATE TABLE nc_twofactor_webauthn_regs;
DELETE FROM nc_twofactor_providers where provider_id = 'webauthn';
```
which contained dead rows.
It seems working now but I would like to be sure that I've no leftovers. Are these the only tables I need to care about?:
```
MariaDB [nextcloud]> show tables LIKE 'nc_twofactor%';
+-------------------------------------+
| Tables_in_nextcloud (nc_twofactor%) |
+-------------------------------------+
| nc_twofactor_backupcodes            |
| nc_twofactor_providers              |
| nc_twofactor_totp_secrets           |
| nc_twofactor_u2f_registrations      |
| nc_twofactor_webauthn_regs          |
+-------------------------------------+
5 rows in set (0.001 sec)
```
Are there any tables from the old u2f-app, which aren't used anymore and can be deleted?

**Comment by st3iny** [comment]
@Somebodyisnobody The nc_twofactor_u2f_registrations table can be dropped. The others are still required.

* `nc_twofactor_backupcodes` => Backup codes
* `nc_twofactor_providers` => general registration table that maps users to enabled providers
* `nc_twofactor_totp_secrets` => TOTP
* `nc_twofactor_u2f_registrations` => **Delete** (belongs to old u2f provider app)
* `nc_twofactor_webauthn_regs` => Belongs to this app here

**Comment by Somebodyisnobody** [comment]
Thank you for clarifying
