### ISSUE TITLE
NC 25.0.3: cant disable twofactor login! 

### ISSUE THREAD

**Issue by g6094199** [nextcloud/twofactor_webauthn#336]
### Steps to reproduce
1. 
2.
3.

### Expected behaviour

enforce twofactor is **disabled** and  **no** other twofactor ist enabled.

on login:
1. when webauthn is disabled
2. when webauthn is **deinstalled**
3. when all keys are disabled
4. when no key is paired

**no** twofaktor auth is requested.

### Actual behaviour
in fact in **all** of the cases above twofactor **IS** requested at login.

like so 

![Bildschirmfoto vom 2023-01-27 19-16-19](https://user-images.githubusercontent.com/37833326/215183047-ae1b1c98-ba66-4b5d-9a6a-cb26f1f6ec7f.png)

when i add a twofactor key i can login.

in database its always enabled for my user:
 webauthn                         | userXYZ   |       1

cant get rid of this ....

### Server configuration

**Operating system**:
alpine 3.17
**Web server:**
nginx 1.22
**Database:**
10.6.11
**PHP version:**
8.1
**Version:** (see admin page)
25.0.3
**Updated from an older version or fresh install:**
update
**List of activated apps:**
`Enabled:
  - audioplayer: 3.3.1
  - breezedark: 24.0.3
  - calendar: 4.2.2
  - circles: 25.0.0-alpha.0
  - cloud_federation_api: 1.8.0
  - contacts: 5.0.3
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_videoplayer: 1.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - maps: 0.2.5
  - music: 1.8.1
  - news: 20.0.1
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - ocsms: 2.2.0
  - photos: 1.7.1
  - polls: 4.1.2
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - spreed: 15.0.3
  - tasks: 0.14.5
  - theming: 2.0.1
  - twofactor_webauthn: 1.0.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - activity: 2.13.4
  - admin_audit
  - bruteforcesettings: 2.5.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - encryption: 1.0.0
  - files_antivirus: 3.3.1
  - firstrunwizard: 1.1
  - geoblocker: 0.5.7
  - integration_moodle: 1.0.2
  - password_policy: 1.4.0
  - recommendations: 0.8.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.7.0
  - suspicious_login: 4.3.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - user_ldap
  - user_status: 1.0.1
`

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.xxxxxxxxx.de",
        "trusted_domains": [
            "cloud.xxxxxxxxx.de",
            "192.168.1.249"
        ],
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/apps-appstore",
                "writable": true
            }
        ],
        "trashbin_retention_obligation": "auto",
        "version": "25.0.3.2",
        "default_phone_region": "DE",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "maintenance": false,
        "logtimezone": "Europe\/Berlin",
        "updater.release.channel": "beta",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "06c711b4xc58axe80d626a01ax8f39c3251",
        "installed": true,
        "app_install_overwrite": [
            "calendar",
            "mail",
            "ocsms",
            "caniupdate",
            "audioplayer",
            "files_external_gdrive",
            "polls",
            "spreed",
            "contacts",
            "bruteforcesettings",
            "files_rightclick",
            "talk_simple_poll",
            "maps",
            "music",
            "breezedark",
            "files_external_ipfs",
            "twofactor_u2f"
        ],
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}

```

**Comment by ChristophWurst** [comment]
> cant get rid of this shit.

https://nextcloud.com/contribute/code-of-conduct/
