### ISSUE TITLE
WebAuthN Key used as 1st factor shouldn't be accepted as 2nd

### ISSUE THREAD

**Issue by jc97** [nextcloud/twofactor_webauthn#378]
### Steps to reproduce
1. Register a YubiKey as a login device in the personal security settings
2. Register the same YubiKey as security device for 2FA
3. Logout
4. Login using the YubiKey
5. Pass 2FA using the same YubiKey

### Expected behaviour
The YubiKey shouldn't be accepted as second factor.

### Actual behaviour
The YubiKey is accepted for both login steps. Thus it is not a two-factor authentication. It's just one factor.

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/server/issues/21215 and related. The two systems don't talk to each other at the moment. For the time being don't register the same key for both systems.
