### ISSUE TITLE
Wrong labeled buttons when activating 2FA

### ISSUE THREAD

**Issue by gituser789** [nextcloud/twofactor_webauthn#385]
### Steps to reproduce
1. Activate 2FA
2. Password window pops up to verify yourself by password
3. see wrong button labels

### Expected behaviour
Button e.g. `OK` and `Abbrechen`

### Actual behaviour
Button `Bestätigen` and `Ja` are displayed, what is practically the same.

### Server configuration
Two-Factor WebAuthn `1.1.2`

**Version:** (see admin page)
Nextcloud 25.0.6

**Updated from an older version or fresh install:**
Updated from an older version

![image](https://github.com/nextcloud/twofactor_webauthn/assets/62549000/6657ad40-4929-4bcf-ba56-dd1776c48762)

**Comment by st3iny** [comment]
The password confirmation dependency is horribly outdated. Updating it should fix this issue as the modal is part of this dependency.
