### ISSUE TITLE
TOTP still required when using WebAuthn

### ISSUE THREAD

**Issue by tessus** [nextcloud/twofactor_webauthn#475]
### Question

I am not entirely sure, but I believe the login flow is either broken or wrongly designed.

#### Summary

I have setup my user account with TOTP. Then I have additionally created a passwordless login:

```
Passwordless Authentication

Set up your account for passwordless authentication following the FIDO2 standard. 
```

This works without any issues. However, when I use the passkey to login, the login flow still asks me for a TOTP. This should not be the case. TOTP should only be requested for user and password authentication. Afaik this is the workflow Google, Github, and all others use. As soon as passkeys are used, there is no need for TOTP (and thus not requested).

Am I wrong or is this an oversight in the Nextcloud login flow?

P.S.: It also possible that I have opened this issue/question in the wrong repo, in which case, please direct me to the correct one.

**Comment by ChristophWurst** [comment]
Passwordless login !== twofactor_webautn

see https://github.com/nextcloud/server/issues/21215. closing as dup.

**Comment by tessus** [comment]
@ChristophWurst thanks for the answer. So just to clarify. The passwordless login setup is not part of the 2FA code? Well, wouldn't the 2FA code be responsible for just not sending a 2FA challenge when the core does not use user/password, but passwordless login? In this case it is a 2FA issue, is it not?

Besides, the other issue has been open for more than 3 years. Isn't proper login flow more important than sitting on it for over 3 years? I understand that the devs always like to add new features, but why is it that essiantial (basic) issus are ignored and kept open for years? I don't want to offend anyonw, but I am genuinly asking, because I don't understand. I am a dev myself and for me and in my projects it is more important to get the basics right, before developing new (probably also not fully working) features.

**Comment by socram70** [comment]
It seems that this is still unaddressed 2.5 years later? I agree with @tessus that TOPT shouldn't be required for passkeys which are used via WebAuthn. Are there any plans to address this?

**Comment by tessus** [comment]
@socram70 This issue has been closed for 3 years now. With Nextcloud one can either use TOTP or passkeys, but not both at the same time (unless you want to enter 2FA even when using passkeys).

**Comment by socram70** [comment]
Thank you, I noticed this too and that it's also discussed in the other thread. However, I don't think that either TOTP or passkeys makes sense, as TOTP together with passwords makes sense, but it doesn't make sense for passkeys. However, this issue is probably the wrong place to discuss this.

**Comment by tessus** [comment]
@socram70 I agree which you, which is why I opened this issue in the first place.

But I can't do anything, if the devs ignore industry standards and opt for a login flow that is not used anywhere else.
