### ISSUE TITLE
Fix deprecations regarding `webauthn-lib`

### ISSUE THREAD

**Issue by st3iny** [nextcloud/twofactor_webauthn#500]
`The argument \"timeout\" is deprecated since version 3.3 and will be removed in 4.0. Please use the method \"setTimeout\". at /home/richard/src/nextcloud/master/dev_apps/twofactor_webauthn/vendor/web-auth/webauthn-lib/src/PublicKeyCredentialOptions.php#40`

**Comment by susnux** [comment]
Required for #573

**Comment by susnux** [comment]
So this is fixed @st3iny ?

**Comment by st3iny** [comment]
I'm not sure if I fixed all deprecation warnings. At least this one is fixed.

Let's open new issues when other critical deprecation warnings are spotted.
