### ISSUE TITLE
Invitation to move this repo to the nextcloud organization

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/twofactor_webauthn#73]
**Is your feature request related to a problem? Please describe.**

We (Nextcloud Gmbh) have a twofactor_u2f app that stopped working with Chrome, due to a intentionally shutdown of the u2f API. Your app is building on the same code base and webauthn replaces the u2f app. It makes sense if we join our efforts and work on your app together.

@michib would you be okay with that? We can also discuss privately if you prefer :v: 

**Describe the solution you'd like**

* Move the app into https://github.com/nextcloud/
* Set up Transifex and add localization anywhere it's not already used
* Set up our usual CI actions based on Github actions
* Set up automated releases via https://github.com/nextcloud-releases/
* Possibly do some code reviews and/or apply Nextcloud coding standards if not there yet
* Reopen https://github.com/michib/nextcloud_twofactor_webauthn/issues/6 and write migration code

In the "old" twofactor_u2f
* Phase out the app, warn admins that it won't be maintained in the future and link to this app

**Describe alternatives you've considered**

n/a

**Additional context**

https://github.com/nextcloud/twofactor_u2f/issues/947
https://github.com/nextcloud/twofactor_u2f/issues/947#issuecomment-1030057050

**Comment by michib** [comment]
Hi,

thank you for this invitation. I think that's a great opportunity for this project to finally mature. After all the time its exists, its still not where i would like it to have (as one can see by the old issues about basic stuff). So i will gladly accept the invitation and transfer the ownership of this project to nextcloud.

**Comment by ChristophWurst** [comment]
Thanks a lot @michib!

**Comment by michib** [comment]
Nice :-)

**Comment by My1** [comment]
how would a migration go by the way @ChristophWurst after all I would assume that all extension owned data gets lost upon removal of said extension.

**Comment by ChristophWurst** [comment]
The database tables remain. We can access them from the replacement app.

**Comment by My1** [comment]
also if/when this is done could someone maybe PLEASE look at the passwordless webauthn section of nextcloud itself too, which has been broken for a long time despite checking if the UV bit is set likely not being an overly hard affair.

https://github.com/nextcloud/server/issues/21215
